version: 2.1

jobs:
  build:
    docker:
      - image: circleci/php:7.4-node-browsers
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: Install PHP dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -y libzip-dev zip unzip
            sudo docker-php-ext-install pdo_mysql zip
            composer install --prefer-dist --no-ansi --no-interaction --no-progress --no-scripts
      - run:
          name: Copy .env file
          command: cp .env.example .env
      - run:
          name: Generate application key
          command: php artisan key:generate
      - run:
          name: Check coding style
          command: vendor/bin/phpcs --standard=PSR12 app tests
      - run:
          name: Run tests
          command: vendor/bin/phpunit
      - run:
          name: Check static code analysis
          command: vendor/bin/phpstan analyze
      - save_cache:
          key: composer-cache-{{ checksum "composer.lock" }}
          paths:
            - vendor
            - ~/.composer/cache
      - save_cache:
          key: node-cache-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - store_artifacts:
          path: coverage
          destination: coverage

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              only: main
      - deploy-to-production:
          requires:
            - build
          filters:
            branches:
              only: main
