version: 2.1
jobs:
  build:
    executor:
      name: ubuntu-2004
    steps:
      - checkout
      - run: sudo apt-get update && sudo apt-get install -y unzip
      - run: composer install
      - run: php artisan key:generate
      - run: phpunit
      - run: tar -czvf app.tar.gz .

  deploy:
    machine:
      enabled: true
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Install AWS CLI
          command: |
            sudo apt-get update
            sudo apt-get install -y awscli
      - run:
          name: Transfer files to remote server
          command: |
            scp -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa app.tar.gz ubuntu@ec2-54-174-0-169.compute-1.amazonaws.com:~/app.tar.gz
      - run:
          name: Extract and Deploy files
          command: |
            ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ubuntu@ec2-54-174-0-169.compute-1.amazonaws.com "rm -rf /var/www/html/*"
            ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ubuntu@ec2-54-174-0-169.compute-1.amazonaws.com "tar -xzvf app.tar.gz -C /var/www
