version: 2

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'

      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist

      - name: Run tests
        run: vendor/bin/phpunit

      - name: Create Dummy Artifacts
        run: |
          echo "my artifact file" > /tmp/art-1;
          mkdir /tmp/artifacts;
          echo "my artifact files in a dir" > /tmp/artifacts/art-2;

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: my-artifacts
          path: |
            /tmp/art-1
            /tmp/artifacts
